### ISSUE TITLE
Colander benchmark is wrong

### ISSUE THREAD

**Issue by maximkulkin** [voidfiles/python-serialization-benchmark#2]
I'm not sure why Colander is present in this benchmark: it's not able to get data from Python objects, and relies on (blazingly fast) manually deserialized data (like a "Custom" subject) and then adds useless 0.11s on top of that.

Also, the API is so tangled and has the same structures on both ends so it's not immediately obvious which direction you should be using. I guess the whole benchmark idea is to test "serialization" (which is converting Python objects into primitive data types) while Colander subject does the reverse: it uses "deserialization". Although as I said it looks pretty much the same.

**Comment by voidfiles** [comment]
That's a good question. I personally have a experience with projects that
use Colander both for serialization, and deserialization. That was the main
reason I included it.

But, the second reason I included it is that I wanted to understand the
different API's and the design decisions that lead to them.

I do agree that for many problems Colander is overkill, but Colander has an
interesting place in the Pylons ecosystem.

**Comment by maximkulkin** [comment]
Where can I find real uses of Colander framework? I'm very curious to find out those use cases.

**Comment by voidfiles** [comment]
The main use case I know of is not open source, I will try and do some
googling later to find specific use cases, but the deform library uses
Colander schemas.

http://docs.pylonsproject.org/projects/deform/en/latest/basics.html

**Comment by maximkulkin** [comment]
As far as I understand, the main use case is validation/normalization of payloads. Although it's a valid use case (and some other libraries might support that), it's not a "serialization" process. You could have created a separate benchmark for payload validation, but I think it's incorrect to include Colander in current benchmark.

**Comment by voidfiles** [comment]
Cool, it is a bit of an odd duck for sure. I think I want to see if I can
reach out to someone on colander team and get some feedback from them. I
have been trying to get in touch with each project to get them to look at
the serializers.

**Comment by voidfiles** [comment]
Okay, seems like we have an answer.

https://groups.google.com/d/msg/pylons-devel/JHPEsV-C43k/fFbuPTziCgAJ I'll remove colander.

**Comment by maximkulkin** [comment]
Ok, cool! I like a fairness of this competition!

**Comment by voidfiles** [comment]
code has been merged.
