### ISSUE TITLE
Lollipop name is displayed incorrect in report

### ISSUE THREAD

**Issue by maximkulkin** [voidfiles/python-serialization-benchmark#4]
I'm looking at the code and it looks pretty much the same as other subjects, but for some reason in the report Lollipop name is "subjects.loli" instead of "Lollipop"

**Comment by voidfiles** [comment]
Cool. I can do that. I'm not sure exactly why it's not working.

**Comment by voidfiles** [comment]
Should be fixed in commit https://github.com/voidfiles/python-serialization-benchmark/commit/cc8e2a1d65231158952dd51df01b42f7e0c20e5b 

As soon as the Travis build is done pages should be re-generated.
