### ISSUE TITLE
Many many objects test

### ISSUE THREAD

**Issue by makmanalp** [voidfiles/python-serialization-benchmark#7]
Hi, I thought you might be interested in this. My use case involves dumping data with a lot of rows (~1-20k), which is interesting because startup overhead starts to matter less and per-row overhead starts to matter way more. I modified test_many to do 10k objects, and here's what I got:

```
$ python benchmark.py
Library                  Many Objects (seconds)    One Object (seconds)    Relative
---------------------  ------------------------  ----------------------  ----------
Custom                                  1.98002              0.00846601     1
lima                                    2.11113              0.00892496     1.06616
serpy                                   4.65359              0.0298979      2.3553
Strainer                                7.34726              0.0420859      3.71606
Toasted Marshmallow                     8.28646              0.0476773      4.19119
Lollipop                               35.6176               0.215291      18.0202
Django REST Framework                  39.7232               0.704004      20.3306
Marshmallow                            51.3343               0.365398      25.9995
kim                                    64.5854               0.421743      32.6917

```

The ordering is still the same but the factors between lima, serpy, strainer, toasted are much smaller.

**Comment by voidfiles** [comment]
Thanks for the feedback. I think that would be a good option to be able to run more objects through the system, but I'm not sure i want to make that the standard right now. If you want to submit a PR that allows people to trigger 10k objects instead of 1000 objects i would be interested in that.

**Comment by makmanalp** [comment]
No worries - just thought it might be neat to know. Thanks for the neat benchmark - it definitely helped me!
